-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create a table for the allowed email addresses of the 2 users
CREATE TABLE IF NOT EXISTS public.allowed_emails (
    email TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on allowed_emails
ALTER TABLE public.allowed_emails ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read of allowed_emails for authenticated users" 
    ON public.allowed_emails
    FOR SELECT 
    TO authenticated 
    USING (true);

-- Create the notebook_entries table
CREATE TABLE IF NOT EXISTS public.notebook_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    author_email TEXT NOT NULL DEFAULT (auth.jwt() ->> 'email'),
    content TEXT NOT NULL,
    image_url TEXT,
    page_number INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on notebook_entries
ALTER TABLE public.notebook_entries ENABLE ROW LEVEL SECURITY;

-- Helper function to check if the current user is in the allowed_emails list
CREATE OR REPLACE FUNCTION public.is_allowed_user()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 
        FROM public.allowed_emails 
        WHERE email = (auth.jwt() ->> 'email')
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RLS Policies for notebook_entries
CREATE POLICY "Allow read access for allowed users only" 
    ON public.notebook_entries
    FOR SELECT 
    TO authenticated
    USING (public.is_allowed_user());

CREATE POLICY "Allow insert access for allowed users only" 
    ON public.notebook_entries
    FOR INSERT 
    TO authenticated
    WITH CHECK (
        public.is_allowed_user() AND 
        author_id = auth.uid()
    );

CREATE POLICY "Allow delete access for own entries" 
    ON public.notebook_entries
    FOR DELETE 
    TO authenticated
    USING (
        public.is_allowed_user() AND 
        author_id = auth.uid()
    );

-- Create the bucket for notebook images
INSERT INTO storage.buckets (id, name, public)
VALUES ('notebook-images', 'notebook-images', false)
ON CONFLICT (id) DO NOTHING;

-- RLS Policies for notebook-images bucket

-- 1. Allow authenticated allowed users to view images
CREATE POLICY "Allow download/read of images for allowed users"
    ON storage.objects
    FOR SELECT
    TO authenticated
    USING (
        bucket_id = 'notebook-images' AND
        public.is_allowed_user()
    );

-- 2. Allow authenticated allowed users to upload images
CREATE POLICY "Allow upload of images for allowed users"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (
        bucket_id = 'notebook-images' AND
        public.is_allowed_user() AND
        (owner = auth.uid()::text OR owner IS NULL)
    );

-- 3. Allow authenticated users to delete their own images
CREATE POLICY "Allow delete of own images for allowed users"
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (
        bucket_id = 'notebook-images' AND
        public.is_allowed_user() AND
        owner = auth.uid()::text
    );

-- Populate allowed emails with demo accounts
INSERT INTO public.allowed_emails (email) VALUES 
('user1@example.com'),
('user2@example.com')
ON CONFLICT (email) DO NOTHING;
