-- 1. Create notebooks table
CREATE TABLE IF NOT EXISTS public.notebooks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    invite_code TEXT UNIQUE NOT NULL DEFAULT substring(md5(random()::text), 1, 8),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on notebooks
ALTER TABLE public.notebooks ENABLE ROW LEVEL SECURITY;

-- 2. Create notebook_members table
CREATE TABLE IF NOT EXISTS public.notebook_members (
    notebook_id UUID REFERENCES public.notebooks(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (notebook_id, user_id)
);

-- Enable RLS on notebook_members
ALTER TABLE public.notebook_members ENABLE ROW LEVEL SECURITY;

-- 3. Update/Recreate notebook_entries to belong to a specific notebook
DROP TABLE IF EXISTS public.notebook_entries CASCADE;

CREATE TABLE public.notebook_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    notebook_id UUID REFERENCES public.notebooks(id) ON DELETE CASCADE NOT NULL,
    author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
    author_email TEXT NOT NULL DEFAULT (auth.jwt() ->> 'email'),
    content TEXT NOT NULL,
    image_url TEXT,
    page_number INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on notebook_entries
ALTER TABLE public.notebook_entries ENABLE ROW LEVEL SECURITY;

-- Helper functions for RLS checks

-- Check if a user belongs to a specific notebook
CREATE OR REPLACE FUNCTION public.is_member_of_notebook(notebook_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 
        FROM public.notebook_members 
        WHERE notebook_members.notebook_id = $1 
          AND notebook_members.user_id = auth.uid()
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Check if two users share any notebook (for storage security)
CREATE OR REPLACE FUNCTION public.share_notebook(user_a_id UUID, user_b_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 
        FROM public.notebook_members m1
        JOIN public.notebook_members m2 ON m1.notebook_id = m2.notebook_id
        WHERE m1.user_id = $1 AND m2.user_id = $2
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Policies for notebooks
CREATE POLICY "Allow members to read notebook" ON public.notebooks
    FOR SELECT TO authenticated USING (public.is_member_of_notebook(id));

CREATE POLICY "Allow authenticated to create notebook" ON public.notebooks
    FOR INSERT TO authenticated WITH CHECK (true);

-- Policies for notebook_members
CREATE POLICY "Allow members to view notebook membership" ON public.notebook_members
    FOR SELECT TO authenticated USING (public.is_member_of_notebook(notebook_id));

CREATE POLICY "Allow user to add themselves to notebook with space (< 2 members)" ON public.notebook_members
    FOR INSERT TO authenticated 
    WITH CHECK (
        user_id = auth.uid() AND
        (SELECT count(*) FROM public.notebook_members WHERE notebook_id = notebook_members.notebook_id) < 2
    );

-- Policies for notebook_entries
CREATE POLICY "Allow read entries for notebook members" ON public.notebook_entries
    FOR SELECT TO authenticated USING (public.is_member_of_notebook(notebook_id));

CREATE POLICY "Allow insert entries for notebook members" ON public.notebook_entries
    FOR INSERT TO authenticated 
    WITH CHECK (
        public.is_member_of_notebook(notebook_id) AND 
        author_id = auth.uid()
    );

CREATE POLICY "Allow delete own entries for notebook members" ON public.notebook_entries
    FOR DELETE TO authenticated 
    USING (
        public.is_member_of_notebook(notebook_id) AND 
        author_id = auth.uid()
    );

-- Storage bucket insert if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('notebook-images', 'notebook-images', false)
ON CONFLICT (id) DO NOTHING;

-- Policies for storage.objects
DROP POLICY IF EXISTS "Allow download/read of images for allowed users" ON storage.objects;
DROP POLICY IF EXISTS "Allow upload of images for allowed users" ON storage.objects;
DROP POLICY IF EXISTS "Allow delete of own images for allowed users" ON storage.objects;

CREATE POLICY "Allow download of images for notebook members" ON storage.objects
    FOR SELECT TO authenticated
    USING (
        bucket_id = 'notebook-images' AND
        (owner::uuid = auth.uid() OR public.share_notebook(owner::uuid, auth.uid()))
    );

CREATE POLICY "Allow upload of images for members" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (
        bucket_id = 'notebook-images' AND
        owner::uuid = auth.uid()
    );

CREATE POLICY "Allow delete of own images" ON storage.objects
    FOR DELETE TO authenticated
    USING (
        bucket_id = 'notebook-images' AND
        owner::uuid = auth.uid()
    );
